# ASCII-Font â€º http://patorjk.com/software/taag/
#   ____    ____        _      __   __   _  __  U _____ u   ____     
#  |  _"\U |  _"\ u U  /"\  u  \ \ / /  |"|/ /  \| ___"|/U |  _"\ u  
# /| | | |\| |_) |/  \/ _ \/    \ V /   | ' /    |  _|"   \| |_) |/  
# U| |_| |\|  _ <    / ___ \   U_|"|_uU/| . \\u  | |___    |  _ <    
#  |____/ u|_| \_\  /_/   \_\    |_|    |_|\_\   |_____|   |_| \_\   
#   |||_   //   \\_  \\    >>.-,//|(_ ,-,>> \\,-.<<   >>   //   \\_  
#  (__)_) (__)  (__)(__)  (__)\_) (__) \.)   (_/(__) (__) (__)  (__) 

#------------------------------------------------------------------------------------------------------------

#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'Dknowledge'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'The Drayker Knowledge Base'




#     _____ __________
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ /
#  /____/_____/\____/    Verify Website to Webmaster Tools

# google_author:             
# google_site_verification:  '983u4882u8_exemple_4493054jqew9rew0'
# bing_webmastertools_id:    '0EXEMPLEADFDSIF3440T023JF398UF30439'
# yandex_site_verification:  ''
# alexa_verify_id:           ''











